import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { MaintenanceRequest } from "@/types/maintenance";

export interface PDFData {
  request: MaintenanceRequest;
  requesterName: string;
  generatedAt: string;
}

export class PDFGenerator {
  private static readonly COLLEGE_NAME = "DE LA SALLE JOHN BOSCO COLLEGE";
  private static readonly COLLEGE_ADDRESS =
    "Mangagoy, Bislig City, Surigao del Sur";
  private static readonly REQUEST_TITLE = "PHYSICAL PLANT / FACILITIES REQUEST";

  static generatePDF(data: PDFData): Blob {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // Set font sizes
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    // Add header with college information
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(this.COLLEGE_NAME, 105, 20, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(this.COLLEGE_ADDRESS, 105, 30, { align: "center" });

    // Add title
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(this.REQUEST_TITLE, 105, 50, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    // Add line separator
    doc.setLineWidth(0.5);
    doc.line(20, 60, 190, 60);

    // Main data table using autoTable
    const tableData = [
      [
        data.request.location_building +
          (data.request.location_room
            ? ` - ${data.request.location_room}`
            : ""),
        data.request.description,
        data.request.action_taken || "",
        data.request.supporting_reasons || "",
      ],
    ];

    autoTable(doc, {
      head: [["Location", "Description", "Action Taken", "Supporting Reasons"]],
      body: tableData,
      startY: 70,
      theme: "grid",
      styles: {
        fontSize: 9,
        cellPadding: 3,
        halign: "left",
        valign: "top",
      },
      headStyles: {
        fillColor: [240, 240, 240],
        textColor: 0,
        fontStyle: "bold",
        fontSize: 10,
      },
      columnStyles: {
        0: { cellWidth: 40 }, // Location
        1: { cellWidth: 60 }, // Description
        2: { cellWidth: 50 }, // Action Taken
        3: { cellWidth: 40 }, // Supporting Reasons
      },
    });

    // Get the final Y position after the table
    let adjustedY = (doc as any).lastAutoTable.finalY + 10;

    // Work Evaluation section (only for completed requests)
    if (data.request.work_evaluation && data.request.status === "Completed") {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Work Evaluation:", 20, adjustedY, { align: "left" });
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(data.request.work_evaluation, 20, adjustedY + 10, {
        align: "left",
      });

      // Adjust adjustedY for signature positioning
      adjustedY += 25;
    }

    // Requester Information
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Requester Information:", 20, adjustedY, { align: "left" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${data.requesterName}`, 20, adjustedY + 10, {
      align: "left",
    });
    doc.text(`Date/Time Received: ${data.generatedAt}`, 20, adjustedY + 15, {
      align: "left",
    });

    // Add signatures section
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Signatures:", 20, adjustedY + 35, { align: "left" });
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    // Signature lines with proper labels
    const signatureY = adjustedY + 45;

    // Requested by
    doc.line(20, signatureY, 80, signatureY);
    doc.text("Requested by", 20, signatureY + 5, { align: "left" });

    // Approved by (VP-AASD)
    doc.line(105, signatureY, 165, signatureY);
    doc.text("Approved by (VP-AASD)", 105, signatureY + 5, { align: "left" });

    // Received by (GMS Head)
    doc.line(20, signatureY + 20, 80, signatureY + 20);
    doc.text("Received by (GMS Head)", 20, signatureY + 25, { align: "left" });

    // Add footer
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by Maintenance Facility Management System", 105, 280, {
      align: "center",
    });

    return new Blob([doc.output("blob")], { type: "application/pdf" });
  }

  static downloadPDF(data: PDFData, filename?: string): void {
    const pdfBlob = this.generatePDF(data);
    const url = URL.createObjectURL(pdfBlob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename || `maintenance-request-${data.request.id}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
